// DATA HEAP STRUCTURE, FIRST THE MAX BINARY HEAP
// AS EXPRESSED IN AN ARRAY THE FIRST CHILD IS AT 2N + 1 AND THE SECOND AT 2N + 2
// ALSO, AS EXPRESSED IN AN ARRAY, THE PARENT CAN BE FOUND BY THE FIRST CHILD AT MATH.FLOOR(N - 1 / 2), 
// AND THE SECOND CHILD AT MATH.FLOOR(N - 2 / 2)

